logging:
  level:
    org.zalando.logbook: TRACE

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: fores
    password: 12345
    driverClassName: org.h2.Driver